[package]
name = "dumd"
version = "0.1.0"
edition = "2021"
license = "EPL-2.0"
description = "Markdown document"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
